### PR TITLE
Pull request: Fix to allow putting an env var in baseId field

### PR DESCRIPTION
**Pull request by Hugobox**

### CODE REVIEW

**Comment by moriuchi** [comment]
Dear Hugobox,
Please tell me how to set the environment variable of Node-RED.
I have set up an environment variable to review the content of your request, but I was unable to reference it in Node-RED.
Thank you.

**Comment by Hugobox** [comment]
Hi @moriuchi ! 
The simplest way to set up the environement variable in node-red is in the settings.js file, just add:
process.env.AIRTABLE_BASEID = "12345";

To make sure it is rightly referenced in Node-Red, you can use an inject node set to "env variable" with a value of "AIRTABLE_BASEID". If this corectly prints "12345", then in the airtable node you should be able to use the env var syntax in the baseId and apikey fields. The env var syntax is "${AIRTABLE_BASEID}"

**Comment by Hugobox** [comment]
Also included in this PR is a fix for issue https://github.com/joeartsea/node-red-contrib-airtable/issues/10

**Comment by moriuchi** [comment]
Hi Hugobox,
Thank you for the detailed instructions on how to set environment variables in Node-RED.
I was able to refer to the environment variables set in BaseId successfully.

I also confirmed that the problem of splitting into multiple arrays when the output type is "All records in 1 array" has been resolved.

**Pull request merged**
